.flowconfig
index.js
package.json

[ON-7183] #comment this is the comment i want added

ON-7183 # Fixed export for package

---

CHANGELOG.md
package-lock.json
package.json
src/services/AWSCognitoClient.ts
src/services/s3Submit.ts
src/services/submit.ts
src/services/uploadAttachment.ts
src/submission-service.ts
src/types/big-json.d.ts

Revert "ON-20959 # Removed big-json and update to aws sdk v3"

---

CHANGELOG.md
src/approvals-service.ts

ON-43420 # updated `FormSubmissionApprovalsResponse` type

---

CHANGELOG.md
src/localisation-service.ts
src/payment-service.ts

ON-43531 # Added function to get payment details

---

src/services/api/external-id.ts
src/services/api/receipt-id.ts
src/services/external-id-generation.ts

ON-44534 # update expected return from forms/:formId/receipt-id

---

CHANGELOG.md
src/scheduling-service.ts
src/services/api/scheduling.ts

ON-44623 # added `createNylasSession` to `schedulingService`

---

CHANGELOG.md
package-lock.json
src/services/api/scheduling.ts
src/services/schedulingHandlers.ts
src/services/submit.ts
src/types/submissions.ts

ON-44564 # added support for NYLAS scheduling events

---

src/services/api/scheduling.ts
src/services/schedulingHandlers.ts
src/services/submit.ts

ON-44647 # make schedulingRescheduleUrl optional

---

src/services/api/scheduling.ts

ON-44653 # update nylas API routes

---

CHANGELOG.md
package-lock.json
src/Sentry.ts
src/scheduling-service.ts
src/services/api/scheduling.ts

ON-44818 # Added formSubmissionResult to nylas session function

---

src/services/submit.ts

ON-44824 # Fixed submission going to pending queue when error is throw

---

src/scheduling-service.ts

ON-44839 # Added onBookingConfirmed callback to createNylasNewBookingSession() result

---

package-lock.json
package.json
src/services/schedulingHandlers.ts

ON-44866 # Bumped @oneblink/sdk-core

---

package-lock.json
src/services/schedulingHandlers.ts

ON-44880 # Fixed paymentFormUrl not being stored with scheduling state

---

src/scheduling-service.ts
src/services/api/scheduling.ts
src/services/schedulingHandlers.ts

ON-44887 # Changed form submission result to be returned after successful booking

---

CHANGELOG.md
src/auth-service.ts

ON-44870 # `mfaEnabled` prop to `authService.getCurrentFormsAppUser`

---

CHANGELOG.md
src/services/cognito.ts
src/tenants.ts

ON-45117 # added `productShortName` to `OneBlinkAppsTenant`

---

src/auth-service.ts

ON-45127 # fixed auth service not exporting `generateMfaQrCodeUrl`

---

CHANGELOG.md
src/services/fetch.ts

ON-45295 # Added Cache-Control: no-cache to all fetch requests

---

src/services/fetch.ts

ON-45306 # Changed back to Cache-Control header

---

CHANGELOG.md
package-lock.json
src/payment-service.ts
src/scheduling-service.ts
src/services/schedulingHandlers.ts
src/types/payments.ts

ON-45149 # Added schedulingBooking to response from handlePaymentQuerystring

---

src/payment-service.ts
src/services/schedulingHandlers.ts
src/types/payments.ts

ON-45341 # Fixed incorrect booking details showing on payment receipts

---

package-lock.json
package.json

ON-45262 # Bumped @oneblink/storage

---

package-lock.json
package.json

ON-45352 # Bumped @oneblink/storage

---

CHANGELOG.md
src/submission-service.ts

ON-45369 # added replaceLocation arg to executePostSubmissionAction

---

package-lock.json
package.json

ON-45401 # Bumped @oneblink/storage

---

CHANGELOG.md
package-lock.json
package.json
src/scheduling-service.ts
src/services/api/scheduling.ts
src/services/schedulingHandlers.ts
src/services/submit.ts
src/submission-service.ts
src/types/scheduling.ts
src/types/submissions.ts

ON-45472 # remove support for 'SCHEDULING' submission event

---

CHANGELOG.md
package-lock.json
package.json
src/forms-app-service.ts
src/services/draft-data-store.ts
src/services/submit.ts
src/submission-service.ts
src/types/submissions.ts

ON-45710 # support appless form submissions

---

CHANGELOG.md
src/form-service.ts
src/forms-app-environment-service.ts
src/index.ts

ON-45724 # Added get configuration functions

---

package-lock.json
package.json

ON-45721 # Bumped @oneblink/storage

---

CHANGELOG.md
src/form-service.ts

ON-45807 # Added formsAppEnvironmentId to formService.getForm()

---

CHANGELOG.md
package-lock.json
package.json
src/services/api/submissions.ts
src/submission-service.ts
src/types/submissions.ts

ON-45819 # Added NewFormSubmission.recaptchas

---

CHANGELOG.md
src/form-store-service.ts

ON-45911 # Added scheduled task properties to form store filtering

---

src/approvals-service.ts

ON-46367 # Fix response type

---

CHANGELOG.md
src/services/api/payment.ts
src/services/payment-providers/WestpacQuickStreamPaymentProvider.ts

ON-46261 # Added captchaSiteKey to paymentService.westpacQuickStream.completeTransaction()

---

CHANGELOG.md
src/localisation-service.ts
tests/localisation-service.test.ts

ON-47148 # remove localisationService.getFlatpickrFormats

---

CHANGELOG.md
src/localisation-service.ts

ON-47223 # remove unused dateOnly prop from generateDate

---

CHANGELOG.md
src/auth-service.ts
src/form-service.ts

ON-47602 # Added toCompleteTask option to formService.getForm()

---

src/tenants.ts

ON-47653 # Removed rogue tenant log

---

CHANGELOG.md
package-lock.json
src/form-service.ts

OB-2382 # Added support for sharepoint list column options sets

---

.github/workflows/test.yml
CHANGELOG.md
package-lock.json
src/services/submit.ts

AP-2541 # Added alwaysSubmitViaPendingQueue option when submitting forms

---

CHANGELOG.md
package-lock.json
package.json
src/services/integration-elements.ts

AP-2650 # Added formService.getPointCadastralParcel()

---

package-lock.json
package.json
src/services/integration-elements.ts

AP-2667 # Changed 400 status code errors to pass through

---

src/submission-service.ts

AP-3323 # Fixed pending queue submission processing successfully with failed attachment uploads

---

CHANGELOG.md
package-lock.json
src/approvals-service.ts

MS-308 # Added `getFlowInstanceNodesWithMeta` to `approvals-service`

---

package-lock.json
package.json

MS-440 # Bumped @oneblink/storage

---

CHANGELOG.md
package-lock.json
src/services/api/drafts.ts
src/types/submissions.ts

MS-446 # Add `sectionState` to `NewDraftSubmission`

---

src/services/draft-data-store.ts

MS-460 # Include `sectionState` in `getDraftSubmission()`

---

CHANGELOG.md
package-lock.json
package.json
src/services/prepareSubmissionData.ts

MS-504 # Check maxFileSize for Files element

---

CHANGELOG.md
src/services/prepareSubmissionData.ts

MS-524 # Remove file size logic

---

CHANGELOG.md
src/localisation-service.ts
src/tenants.ts

MS-528 # added `localisationService.getDistanceUnits()`

---

CHANGELOG.md
package-lock.json
src/form-store-service.ts

AP-3938 # Added dateTimeCompleted filter to form store

---

package-lock.json
package.json

AP-3935 # Bumped @oneblink/storage

---

CHANGELOG.md
package-lock.json
package.json

MS-542 # changed `@oneblink/storage`

---

package-lock.json
package.json

AP-4109 # Bumped @oneblink/storage

---

package-lock.json
package.json

AP-4181 # Bumped @oneblink/storage

---

package-lock.json
package.json

AP-4322 # Bumped @oneblink/sdk-core

---

CHANGELOG.md
package-lock.json
src/attachments-service.ts
src/services/prepareSubmissionData.ts

AP-4395 # Added snapshot image uploading for Arc GIS form element

---

package-lock.json
src/attachments-service.ts
src/services/prepareSubmissionData.ts

AP-4442 # update snapshot image uploading for Arc GIS form element

---

package-lock.json
package.json

AP-4489 # Bumped @oneblink/storage

---

CHANGELOG.md
package-lock.json
src/services/uploadAttachment.ts

AP-4588 # Added path to attachments

---

CHANGELOG.md
package-lock.json
src/draft-service.ts
src/services/draft-data-store.ts
src/types/submissions.ts

AP-4909 # added support for public drafts to `draftService`
